---
title: "Data-303 handout"
author: "Adham Rishmawi"
format: 
  html:
    toc: true
    embed-resources: true
    self-contained-math: true
editor: visual
---

## Citations

-   Vallor, S. (2018). *Technology and the virtues: A philosophical guide to a future worth wanting*. Oxford University Press.
-   Pruim, R. (n.d.). 2  ethics for Data Science. Notes for Data 303 - 2  Ethics for Data Science. Retrieved April 10, 2023, from <https://calvin-ds303-notes.netlify.app/ethics/ethical-issues.html#ethical-issues-in-data-science>
-   Shannon Vallor. (n.d.). Retrieved April 11, 2023, from https://www.shannonvallor.net/

## Quick Summary

Devising a balanced relationship with technology is of paramount importance in building an ethical and virtuous society. This concept is explored extensively in Shannon Vallor's book "Technology and the Virtues: A Philosophical Guide to a Future Worth Wanting." By focusing on responsible design, appropriate use and ethics surrounding technology usage alongside cultivating virtues like wisdom, compassion, courage and justice within individuals; one can ensure technology contributes solely to the greater good.

Integrating technology into society while promoting ethical values and human flourishing is the central point of exploration in this insightful book. The text provides readers with a theoretical framework for understanding the intersection between technology and ethics, offering ideas on harmonizing these two often divergent fields.

## Quotes

-   "The challenge we face today is not a moral dilemma; it is rather a moral *imperative*, long overdue in recognition, to collectively cultivate the technomoral virtues needed to confront... emerging technosocial challenges wisely and well."
-   "Markets, as human institutions, are legitimized only by their promotion of human flourishing. To sacrifice the latter to the former is neither pragmatism nor realism---it is insanity."

## Statement

**Eye-opening:** the degree at which we humans are comfortable at being stagnant with how fast technology excels beyond our capabilities.

## 
